---
resources:
- name: repo
  type: git
  source: {uri: https://github.com/joblini/concourse-test.git}

jobs:
  - name: configure-self
    plan:
    - get: repo
      trigger: true
    - set_pipeline: self
      file: repo/pipeline.yml
      var_files:
#     - repo/params.yml
      - repo/((params_file))

  - name: hello
    plan:
      - get: repo
        trigger: true
        passed: [configure-self]
      - task: echo-hello-world
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
#           args: ["Hello yourself!"]
            args: [((helloMessage))]

