---
resources:
- name: repo
  type: git
  source: {uri: https://github.com/joblini/concourse-test.git}

jobs:
  - name: hello
    plan:
      - get: repo
      - task: echo-hello-world
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
#           args: ["Hello yourself!"]
            args: [((helloMessage))]

