---
resources:
- name: repo
  type: git
  source: {uri: https://github.com/joblini/concourse-test.git}

jobs:
  - name: configure-self
    plan:
    - get: repo
      trigger: true
    - set_pipeline: self
      file: repo/pipeline-foo.yml

  - name: set-pipeline
    plan:
    - get: repo
      trigger: true
      passed: [configure-self]
    - set_pipeline: pipeline-foo
      file: repo/pipeline.yml
      var_files:
      - repo/params-foo.yml
      