---
resources:
- name: repo
  type: git
  source: {uri: https://github.com/joblini/concourse-test.git}

jobs:
  - name: configure-self
    plan:
    - get: repo
      trigger: true
    - set_pipeline: self
      file: repo/pipeline.yml
      var_files:
      - repo/params-bar.yml

